dcc_config_type: agents
models: []
context:
  - dcc_use: context/file
  - dcc_use: context/code
  - dcc_use: context/current_file
rules:
  - dcc_use: rules/using_flags
docs:
  - dcc_use: docs/continue_docs
mcpServers: []
name: Main Config
dcc_uri: configs/main
version: "1.1"
schema: v1
description: this is my test configuration to show that multiple definitions can
  be bundled into one
prompts:
  - dcc_use: prompts/check_code_vulnerabilities
  - dcc_use: prompts/unit_test
dcc_tags:
  - angular
  - front-end team
