name: Test Config
dcc_uri: dev/configs/main
version: "1.4"
schema: v1
description: this is my test configuration to show that multiple definitions can
  be bundled into one config file
dcc_tags:
  - angular
  - frontend
dcc_config_type: ide
models: []
context:
  - dcc_use: dev/context/file
  - dcc_use: dev/context/code
  - dcc_use: dev/context/current_file
rules:
  - dcc_use: dev/rules/using_flags
prompts:
  - dcc_use: dev/prompts/check_code_vulnerabilities
  - dcc_use: dev/prompts/unit_test
docs:
  - dcc_use: dev/docs/continue_docs
mcpServers: []
