name: Main Config
dcc_uri: dev/configs/main
version: "1.3"
schema: v1
description: this is my test configuration to show that multiple definitions can
  be bundled into one config file
dcc_tags:
  - angular
  - frontend
dcc_config_type: ide
models: []
context:
  - dcc_use: context/file
  - dcc_use: context/code
  - dcc_use: context/current_file
rules:
  - dcc_use: rules/using_flags
prompts:
  - dcc_use: prompts/check_code_vulnerabilities
  - dcc_use: prompts/unit_test
docs:
  - dcc_use: docs/continue_docs
mcpServers: []
